# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: ["main"]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Set version
        id: version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=dev-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          fi

      - name: Build autoping
        shell: bash
        run: |
          GOOS=windows GOARCH=amd64 go build -o thefinals-autoping-${{ steps.version.outputs.VERSION }}.exe ./cmd/autoping

      - name: Build autoshot
        shell: bash
        run: |
          GOOS=windows GOARCH=amd64 go build -o thefinals-autoshot-${{ steps.version.outputs.VERSION }}.exe ./cmd/autoshot

      - name: Build delayChecker
        shell: bash
        run: |
          GOOS=windows GOARCH=amd64 go build -o lmb-delays-checker-${{ steps.version.outputs.VERSION }}.exe ./cmd/delayChecker

      - name: Upload autoping artifact
        uses: actions/upload-artifact@v6
        with:
          name: autoping-windows-amd64
          path: thefinals-autoping-${{ steps.version.outputs.VERSION }}.exe

      - name: Upload autoshot artifact
        uses: actions/upload-artifact@v6
        with:
          name: autoshot-windows-amd64
          path: thefinals-autoshot-${{ steps.version.outputs.VERSION }}.exe

      - name: Upload delayChecker artifact
        uses: actions/upload-artifact@v6
        with:
          name: lmb-delays-checker-windows-amd64
          path: lmb-delays-checker-${{ steps.version.outputs.VERSION }}.exe

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            thefinals-autoping-${{ steps.version.outputs.VERSION }}.exe
            thefinals-autoshot-${{ steps.version.outputs.VERSION }}.exe
            lmb-delays-checker-${{ steps.version.outputs.VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
